In [43]:
import base64
import numpy as np
import cv2
def get_cv2_image_from_b64(image_b64):
    
    return cv2.imdecode(np.frombuffer(base64.b64decode(image_b64), np.uint8), cv2.IMREAD_COLOR)

def get_b64_from_file(image_file):
    with open(image_file, "rb") as img_file:
        return base64.b64encode(img_file.read()).decode('utf-8')



In [ ]:
import cv2
image_b64  = r"C:\Users\Yaswanth Reddy\SportsPlayerClassifier\model\dataset\test\Joe Biden face\Image_.jpg"
image =(get_cv2_image_from_b64(get_b64_from_file(image_b64)))

In [45]:


img = cv2.imread(image)
cv2.imshow("Image", img)


error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'imread'
> Overload resolution failed:
>  - Expected 'filename' to be a str or path-like object
>  - Expected 'filename' to be a str or path-like object
>  - Expected 'filename' to be a str or path-like object


In [39]:
import base64
import cv2
import os
import numpy as np
from skimage.feature import hog
from skimage import color

In [40]:
def get_preprocessed_image(img_path):
    img = cv2.imread(img_path)
    if img is None:
        raise ValueError(f"Image not found or couldn't be read: {img_path}")

    img = cv2.resize(img, (128, 128))
    gray = color.rgb2gray(img)

    hog_feat = hog(gray, pixels_per_cell=(8, 8), cells_per_block=(2, 2), visualize=False)

    return np.array(hog_feat)

In [41]:
def crop_and_save_face(img_path, output_path):
    img = cv2.imread(img_path)
    if img is None:
        raise ValueError(f"Could not read image at {img_path}")
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)

    for (x, y, w, h) in faces:
        face_crop = img[y:y+h, x:x+w]
        face_resized = cv2.resize(face_crop, (128, 128))
        cv2.imwrite(output_path, face_resized)
        print(f"✅ Face saved to: {output_path}")
        return output_path  # Return the output path or image if needed

    print("⚠️ No face detected in the image.")
    return None


In [62]:
image_b64  = os.path.join(os.getcwd()+"\server\images\input", "Image_3.jpg")
output_path = os.path.join(os.getcwd()+"\server\images\output","3.jpg")
result = crop_and_save_face(image_b64, output_path)

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Yaswanth Reddy\AppData\Local\Temp\ipykernel_6580\1051273834.py:1: SyntaxWarning: invalid escape sequence '\s'
  image_b64  = os.path.join(os.getcwd()+"\server\images\input", "Image_3.jpg")
C:\Users\Yaswanth Reddy\AppData\Local\Temp\ipykernel_6580\1051273834.py:2: SyntaxWarning: invalid escape sequence '\s'
  output_path = os.path.join(os.getcwd()+"\server\images\output","3.jpg")


✅ Face saved to: c:\Users\Yaswanth Reddy\SportsPlayerClassifier\server\images\output\3.jpg


In [63]:
image_b64  = os.path.join(os.getcwd()+"\server\images\input", "2.jpg")
image_b64

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Yaswanth Reddy\AppData\Local\Temp\ipykernel_6580\1270830166.py:1: SyntaxWarning: invalid escape sequence '\s'
  image_b64  = os.path.join(os.getcwd()+"\server\images\input", "2.jpg")


'c:\\Users\\Yaswanth Reddy\\SportsPlayerClassifier\\server\\images\\input\\2.jpg'

In [46]:
result

'c:\\Users\\Yaswanth Reddy\\SportsPlayerClassifier\\server\\images\\output\\7.jpg'

In [64]:
img = get_preprocessed_image(result)
img 

array([0.05874874, 0.        , 0.        , ..., 0.        , 0.        ,
       0.        ])

In [57]:
len(img)

8100

In [65]:
img= img.reshape(1,-1)
img.shape

(1, 8100)

In [ ]:
import numpy as np
import joblib


model = joblib.load(r'C:\Users\Yaswanth Reddy\SportsPlayerClassifier\server\artifacts\model.pkl')




array([0], dtype=int64)

In [75]:
X_reduced = img.flatten()
result = model.predict([X_reduced])
proba = model.predict_proba([X_reduced])*100
result

array([12], dtype=int64)

In [67]:
cls = result.tolist()[0]
cls

12

In [68]:
import json


with open(r'C:\Users\Yaswanth Reddy\SportsPlayerClassifier\server\artifacts\classes.json', 'r') as f:
    data = json.load(f)
classes = {int(v): k for k, v in data.items()}



In [69]:
classes[cls]

'Rahul Gandhi'

In [78]:
max(np.round(proba.tolist(),2))

array([ 1.69,  1.41,  0.75,  1.76,  1.7 ,  1.  ,  0.58,  1.63,  7.88,
        0.61,  2.78,  3.86, 37.69,  0.62,  3.97,  0.7 , 12.87,  0.82,
       17.12,  0.57])